ForceUpdate := checkUpdate.Bind(True)

A_TrayMenu.Tip :=        "WingmanReloaded Dev Ver" VersionNumber
A_TrayMenu.Delete()
A_TrayMenu.Add(         "WingmanReloaded", optionsCommand)
A_TrayMenu.Default :=    "WingmanReloaded"
A_TrayMenu.Add()
A_TrayMenu.Add(         "Project Site", LaunchSite)
A_TrayMenu.Add()
A_TrayMenu.Add(         "Make a Donation", LaunchDonate)
A_TrayMenu.Add()
A_TrayMenu.Add(         "Run Calibration Wizard", CalibrationWizard)
A_TrayMenu.Add()
A_TrayMenu.Add(         "Print Object", PromptForObject)
A_TrayMenu.Add()
A_TrayMenu.Add(         "Custom Loot Sort", LaunchLootFilter)
A_TrayMenu.Add()
A_TrayMenu.Add(         "Refresh Chaos Data", RefreshChaosRecipe)
A_TrayMenu.Add()
A_TrayMenu.Add(         "Open FindText interface", ft_Start)
A_TrayMenu.Add()
A_TrayMenu.Add(         "Window Spy", WINSPY)
A_TrayMenu.Add()
A_TrayMenu.Add(         "Force Update", ForceUpdate)
A_TrayMenu.Add()
A_TrayMenu.Add(         "Reload This Script", RELOAD)
A_TrayMenu.Add()
A_TrayMenu.Add(         "Exit", QuitNow) ; added exit script option
